# Generated by Django 3.0 on 2020-03-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0002_auto_20200331_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default-avtar.jpg', null=True, upload_to='users/'),
        ),
        migrations.AlterModelTable(
            name='userdetail',
            table='user_details',
        ),
    ]
