# Generated by Django 3.0 on 2020-03-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0004_auto_20200331_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default-avtar.png', null=True, upload_to='users/'),
        ),
    ]
