# Generated by Django 3.0 on 2020-04-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0005_auto_20200401_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(choices=[(1, 'male'), (0, 'female'), (2, 'other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
