# Generated by Django 3.0 on 2020-04-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0006_auto_20200401_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(choices=[(1, 'male'), (0, 'female'), (2, 'other')], max_length=1, null=True),
        ),
    ]
