# Generated by Django 3.0 on 2020-04-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0007_auto_20200401_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (0, 'Female'), (2, 'Other')], max_length=1, null=True),
        ),
    ]
