# Generated by Django 3.0 on 2020-03-17 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('room_type', models.CharField(choices=[('0', 'freshman'), ('1', 'sophomore'), ('2', 'junior'), ('3', 'senior')], max_length=1)),
                ('price', models.IntegerField()),
                ('details', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='static/rooms/')),
                ('is_publish', models.CharField(choices=[('0', 'false'), ('1', 'true')], max_length=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
