# Generated by Django 3.0 on 2020-03-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0003_auto_20200317_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_publish',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=1),
        ),
    ]
