# Generated by Django 3.0 on 2020-03-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0004_auto_20200317_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
