# Generated by Django 3.0 on 2020-03-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0005_room_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
