# Generated by Django 3.0 on 2020-03-17 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0007_auto_20200318_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
