# Generated by Django 3.0 on 2020-03-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0008_auto_20200318_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
    ]
