# Generated by Django 3.0 on 2020-03-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0009_auto_20200318_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(null=True, upload_to='static/rooms/'),
        ),
    ]
