# Generated by Django 3.0 on 2020-03-19 18:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppAdmin', '0013_roombooking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomBooking',
            new_name='RoomOrders',
        ),
        migrations.AlterModelTable(
            name='roomorders',
            table='room_orders',
        ),
    ]
