# Generated by Django 3.0 on 2020-03-19 18:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppAdmin', '0014_auto_20200320_0001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomOrders',
            new_name='RoomOrder',
        ),
        migrations.AlterModelTable(
            name='roomorder',
            table='room_order',
        ),
    ]
