# Generated by Django 3.0 on 2020-03-31 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0019_auto_20200331_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomorder',
            old_name='room_id',
            new_name='room_no',
        ),
    ]
