# Generated by Django 3.0 on 2020-03-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0020_auto_20200401_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomorder',
            old_name='room_no',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='roomorder',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='roomorder',
            name='order_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
