# Generated by Django 3.0 on 2020-04-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0022_auto_20200401_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_publish',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
