# Generated by Django 3.0 on 2020-04-04 05:23

import AppAdmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0025_auto_20200401_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomorder',
            name='order_no',
            field=models.CharField(blank=True,  max_length=255, null=True, unique=True),
        ),
    ]
