# Generated by Django 3.0 on 2020-04-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0030_auto_20200405_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomorder',
            name='order_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
